### PR TITLE
Example drawing objects with different vertex formats

### PR DESCRIPTION
**Pull request by einarf**
- Modified `visualization` to support drawing different vertex formats.
- Simple box drawing example showing that `visualization` can draw objects with 6 different vertex formats.

Left: Unlit box with and without texture
Center: Vertex color with and without texture
Right: Lighting with and without texture (meaning normals are present)

The `draw()` function automatically detects what modes are needed.

screen shot 2018-06-08 at 20 59 35

### CODE REVIEW

**Comment by einarf** [comment]
The last thing I can think of now is that README needs a lot of updating. It's the front of the project and is the most important thing getting users and contributors for the project.

**Comment by greenmoss** [comment]
I did a reverse image search. The earliest version of this image I could find is here:

http://www.gaanza.com/blog/loading-imagetexture-mapping-in-lwjgl/

No provenance, no license. I guess we'll call this good, and if someone reports a violation we can change to something else.

**Comment by greenmoss** [comment]
On the `README.md`, do you have anything you would like to see updated?

**Comment by einarf** [comment]
The image was used a lot by the nehe guides back in the days. It was originally from some other development kit and is generally spread all over the place in all kinds of modified versions.

**Pull request merged**
