### PR TITLE
Allow users to override material parser

### PR DESCRIPTION
**Pull request by einarf**
We should allow users to override the material parser. They can simply make a subclass of the obj parser.

```python
class CustomObjParser(ObjParser):
    material_parser_cls = CustomMaterialParser

class CustomWavefront(Wafefront):
    parser_cls = CustomObjParser

scene = CustomWavefront(...)
```

This is a lot less hassle than overriding methods possibly breaking forward compatibility.

### CODE REVIEW

**Comment by greenmoss** [comment]
Is this related to #53?

Seems like a test case would be useful here.

**Comment by einarf** [comment]
Not sure how to actually test this as it's the users responsibility to write a working parser. If you had any specific idea, don't hesitate to share it.

Seems I need to rebase this before merge anyway.

**Comment by einarf** [comment]
All done. Still not sure what test would cover this other than all existing parser tests.

**Comment by einarf** [comment]
This is not related to #53. It's just to allow people to override the material parser.

**Pull request merged**
