### PR TITLE
Made Pyglet an optional dependency

### LINKED ISSUE #24: Pyglet dependency should be optional/extra
As you state in the readme.md

> This python module allows you to read Wavefront 3D object files (something.obj and something.mtl) and use them as Python objects. Currently Pyglet is required to render and display these objects.

Objective: create python objects with obj file data. pyglet is totally optional and your package should reflect this.

https://github.com/greenmoss/PyWavefront/blob/4e47c1561b0d0bc3089c695ac151513f58eebe4d/pywavefront/__init__.py#L35
Importing pyglet at this level makes it required. It should only be imported when actually needed.

### PR DESCRIPTION
**Pull request by SergioRAgostinho**
This requires prior merging of #28 (and #29 ). Once those are done I'll update the PR. Also apologies,  for the PR leakage but I needed to be able to run the unit tests without much hassle. You basically only need to look at the last two commits.

The main idea behind my implementation was to move everything pertaining graphics handling to a visualization file. Without having pyglet you're completely able to load all .obj data into an object. If you want to invoke `draw()`, `pywavefront.visualization` needs to be imported. Invoking `draw()` without the import will raise an exception telling you to import the file.

Once visualization is imported, the classes are totally populated with the legacy functionality for drawing. I did things in a way that you only need to import visualization if you really want to visualize things. It handles gracefully situations in which data is loaded into an object prior to importing visualization, and only then the import is made.

Closes #24 .

**Edit:** I only tested this for Python 3.5. I'm not sure it is compatible with 2.

### CODE REVIEW

**Comment by greenmoss** [comment]
Seems like a good approach to me. Thanks for the PR!

I merged #29. I added a comment to #28; please review when you get a chance.

**Comment by SergioRAgostinho** [comment]
Found out the examples and the README need updates to be consistent.

**Comment by greenmoss** [comment]
@SergioRAgostinho reviewed changes, ready to merge.

Are you going to add README/example updates too?

**Comment by SergioRAgostinho** [comment]
> Are you going to add README/example updates too?

Yes. I'm going to rebase things now and then have a look a both.

**Comment by SergioRAgostinho** [comment]
Should be good to go now.

**Comment by greenmoss** [comment]
FWIW, python 2 tests pass:

https://circleci.com/gh/greenmoss/PyWavefront/18?utm_campaign=build-failed&utm_medium=email&utm_source=notification

**Pull request merged**
